not_NE = ['Sheep', 'FISH', 'Plastic', 'Bottled', 'Atlas', 'Water', 'Longer', 'Bottle', 'THE', 'Bright', 'SIERIOUS', 'Everybody'
'Well', 'Simply Written', 'Allot', 'Whereas', 'Common', 'Personal', 'Human', 'School', 'Kids', 'SCHOOL', 'BAD'
'High School', 'STUPID AND GAY', 'Hey IE', 'Spam', 'PCs', 'UNIVERSAL', 'RAM', 'Well','Till', 'Task Manager', 'FFX', 'IE',
'THE POSITION TO', 'FOLLOW HIM', 'Imagine', 'HE', 'Sultan', 'Dutch', 'British', 'BOSS', 'Chinese', 'Nope', 'Kids', 'Parents', 'Children', 'No',
'Lack', 'FAT', 'Definattley', 'PE', 'Obesity', 'Physical', 'Mother', 'Lousy Father', 'Eighteen Years', 'Fatherless',
'DO', 'Murder', 'Nobody', 'Yeh', 'Men', 'SHE', 'RAPE', 'Bottled', 'European','American', 'Which', 'Pray', 'God', 'Please', 'None', 'Geological', 
'Religion', 'Fossil', 'Lord', 'Sorry', 'Jesus', 'YOUR', 'Define', 'Life', 'xD', 'Fruit', 'Sean', 'FINAL', 'Evolution', 'Eden', 'Solid', 'Science', 
'AGAINST', 'Evolved', 'Existence', 'YOU', 'Heart', 'Japanese', 'ACTUALLY', 'Hair', 'Gaps', 'ULTIMATE', 'BRANCH', 'Speciation', 'NOT', 'Earth', 'Creationism', 
'Bacteria', 'Radiometric', 'Asian Garden', 'African Garden', 'Which', 'God', 'Girls', 'Same', 'Religion', 'Does', 'TRUTH',
'Sin', 'SISTER', 'Gay', 'UNPROTECTED', 'HOMOSEXUALITY', 'Guys', 'U.S.', 'BROTHER', 'Marriage', 'WHOLE', 'Homosexuality', 
'Fair', 'Civil', 'ONLY', 'Church', 'Guy AND Girl', 'IETab', 'TABS', 'IE Firefox', 'Main','IE Supporters','HTML', 'Toolbar', 'Seperate', 'FireFox', 
 'LISTLESS', 'Security', 'IE', 'Only Reason', 'BTW', 'Hell', 'Love', 'Yea', 'Nobody', 'loCo', 'HECK YES', 'QUICKNESS', 'Murder', 'Ofcourse', 'Nah',
 'BOO', 'WILL', 'Good', 'IITians', 'Nobody', 'SAY', 'Western', 'Kill', 'Strong', 'CORRUPTION', 'Pakistan China', 'British', 'Americas', 'Hahaha', 'Whooo', 
 'Americans', 'Brits', 'NOT', 'Evolution', 'Creation', 'Old', 'Biblical', 'God', 'HINT', 'Adam', 'HAVE', 'Darwinism', 'True', 'Radiometric', 'Oops', 'Core', 
 'Physical Education', 'AP', 'FUN', 'Physical Ed', 'WRONG', 'NOT', 'Sport', 'Physical', 'EVERYONE', 'Bottom', 'God', 'Please', 'Christianity',  'Civil Union', 
 'Life', 'Christian', 'Gay', 'Gay Marriage', 'Second', 'LONG', 'Wrong','Marriage', 'Love', 'Nature', 'Enough', 'Are', 'NOT', 'Hell', 'Merica', 'DOES', 'BEST', 
 'Full', 'Believe', 'POTENTIAL', 'POTENTIAL TO', 'NAMASTE', 'WILL', 'Earth',
 'BUT WE', 'ALso', 'BUT', 'BEHIND', 'SCIENCE', 'FACTS', 'FLOOD OF NOAH HAPPENED', 'PERFECT', 'Bible', 'Science', 'REMAINS OF LONG', 'Atheism', 'FLOOD', 'AT',
  'Notmymuse', 'INTELLIGENT', 'ALL', 'Eh', 'Agnostic', 'SAME', 'ANIMALS AND', 'DINOSAUR', 'THE WORLD', 'HAHAHA', 'BONES', 'ANY', 'Islam',
 'WE', 'God', 'ROFL', 'Books', 'Black', 'Sponge', 'School', 'Good', 'Less', 'Okay Look', 'SCHOOL', 'UNIFORM', 'Bad', 'Teenager', 'Student', 'WHY', 'GOOOOOOOOOD IDEA',
  'Island', 'William Farquhar Singapore', 'William', 'Everybody', 'Murder', 'Love', 'FAMILY', 'Family', 'No', 'Anyone', 'Marriage', 'Gene', 'Hmmm', 'PORN', 'YUR', 'Christian', 
  'NORMAL', 'MIRROR AND', 'Porn', 'WATCH', 'CUZ', 'TO', 'WRONG', 'Rape', 'Wrong', 'Sexual Abuse', 'WHY', 'Addictive', 'REALLY', 'FAITH',  'Christ', 'God', 'Gravity', 'BEST', 'THATS',  
  'Faith', 'Evolution','Science', 'MUSLIM', 'Greek', 'Roman', 'Makes', 'Everyone', 'LIKE', 'Whoever', 'Porn', 'Absolutley', 'Sex', 'Easy', 'Pornography', 'Mabye', 'Nope', 'Listen', 'English', 
  'LOL', 'Which', 'BOOKZ SUCK', 'Exercise', 'TV', 'SPELL', 'Baseball', 'OLDEN DAYS', 'Imagine', 'Television', 'WAY', 'GO','DVDs', 'Books', 'SO', 'SAVED']